export const routeRedirects = {
    '/assets/cache_image/**': { redirect: { to: '/', statusCode: 301 } },
    '/index.html': { redirect: { to: '/', statusCode: 301 } },
    '/ru/index.html': { redirect: { to: '/ru', statusCode: 301 } },
    '/index.htm': { redirect: { to: '/', statusCode: 301 } },
    '/ru/index.htm': { redirect: { to: '/ru', statusCode: 301 } },
    '/index.php': { redirect: { to: '/', statusCode: 301 } },
    '/ru/index.php': { redirect: { to: '/ru', statusCode: 301 } },
    '/default.asp': { redirect: { to: '/', statusCode: 301 } },
    '/ru/default.asp': { redirect: { to: '/ru', statusCode: 301 } },
    '/default.aspx': { redirect: { to: '/', statusCode: 301 } },
    '/ru/default.aspx': { redirect: { to: '/ru', statusCode: 301 } },
    '/home': { redirect: { to: '/', statusCode: 301 } },
    '/ru/home': { redirect: { to: '/ru', statusCode: 301 } },
    '/front': { redirect: { to: '/', statusCode: 301 } },
    '/ru/front': { redirect: { to: '/ru', statusCode: 301 } },
    '/files/**': { redirect: { to: 'https://admin.healthydent.ua/files/**' } },
    '/cron.php': { redirect: '/' },
    '/assets/components/**': { redirect: { to: '/', statusCode: 301 } },
    '/_nuxt/components/**': { redirect: { to: '/', statusCode: 301 } },
    '/assets/uploads/**': { redirect: { to: '/', statusCode: 301 } },
    '/templates/main/**': { redirect: { to: '/', statusCode: 301 } },
    '/ru/files/images/**': { redirect: { to: '/ru', statusCode: 301 } },
    '/ru/assets/components/**': { redirect: { to: '/ru', statusCode: 301 } },
    '/ru/assets/cache_image/**': { redirect: { to: '/ru', statusCode: 301 } },
    '/ru/templates/main/': { redirect: { to: '/ru', statusCode: 301 } },
    '/ru/files/pdf/**': { redirect: { to: '/ru', statusCode: 301 } },
    '/sites': { redirect: '/', statusCode: 301 },
    '/sites/**': { redirect: '/', statusCode: 301 },
    '/misc': { redirect: '/', statusCode: 301 },
    '/misc/**': { redirect: '/', statusCode: 301 },
    '/dental-tourism/sites': { redirect: '/', statusCode: 301 },
    '/dental-tourism/sites/**': { redirect: '/', statusCode: 301 },
    '/api/v1/get-static-data': { redirect: '/', statusCode: 301 },
    '/en/api/v1/get-static-data': { redirect: '/en/dental-clinic-kyiv', statusCode: 301 },
    '/ru/api/v1/get-static-data': { redirect: '/ru', statusCode: 301 }
}