export const MODALS_KEYS = {
    BURGER: 'BURGER',
    SERVICES: 'SERVICES',
    VIDEO: 'VIDEO',
    APPOINTMENT: 'APPOINTMENT',
    HOT_TIME: 'HOT_TIME',
    REVIEW: 'REVIEW',
    SUCCESS: 'SUCCESS'
}